config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :transactions
  resources :accounts
  resources :agencies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'accounts#index'
end

app/models/agency.rb
class Agency < ApplicationRecord
    has_many :accounts
    validates :ag, :address, presence: true
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: [:show, :edit, :update, :destroy]

  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(agency_params)
    respond_to do |format|
       if @agency.save
         format.json { head :no_content }
         format.js     
       else
         format.json { render :json => { :error => @agency.errors.full_messages }, :status => 422 }
       end
     end
   end

  # PATCH/PUT /agencies/1
  # PATCH/PUT /agencies/1.json
  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: 'Agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_params
      params.require(:agency).permit(:ag, :address)
    end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_agency.html.erb
<%= agency.ag%>

app/views/agencies/_form.html.erb
<%= form_with(model: agency, remote: true,id:'agency') do |form| %>
  <% if agency.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(agency.errors.count, "error") %> prohibited this agency from being saved:</h2>

      <ul>
        <% agency.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>
      <div class="row">
        <div class="input-field col s12">
          <i class="material-icons prefix">account_balance</i>
          <%= form.label 'Número da Agência' %>
            <%= form.text_field :ag, id: :agency_ag, class:'validate' %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <i class="material-icons prefix">location_on</i>
          <%= form.label 'Endereço' %>
            <%= form.text_field :address, id: :agency_address, class:'validate' %>
        </div>
      </div>
      <div class="actions">
       <!-- <%= form.submit %>-->
      </div>
      <% end %>

app/views/agencies/_new_agency.html.erb
<div class="modal-content">
      <h4>Nova Ideia</h4>
      <%= render 'form', agency: @agency %>
</div>
<div class="modal-footer">
  <!--<a id="submit-idea" class="waves-effect waves-green orange btn-flat ">Salvar</a>-->
  <a href="#!" class=" modal-close waves-effect waves-green btn-flat ">Cancelar</a>
</div>

app/views/agencies/create.js.erb
$("#modal").modal('close');
$('#agencies').append('<%= j render (@agency) %>')  

app/views/agencies/edit.html.erb
<h1>Editing Agency</h1>

<%= render 'form', agency: @agency %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>

app/views/agencies/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Agencies</h4>

<table class="centered highlight responsive-table">
  <thead>
    <tr>
      <th>Ag</th>
      <th>Endereço</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agencies.each do |agency| %>
      <tr>
        <td><%= agency.ag %></td>
        <td><%= agency.address %></td>
        <td><%= link_to 'Edit', edit_agency_path(agency) %></td>
        <td><%= link_to 'Destroy', agency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="agencies">
</div>
<%= link_to  new_agency_path,class:'btn-floating btn-large waves-effect waves-light red', remote: true do %>
<i class="material-icons">add</i>  
<%end%>

app/views/agencies/new.js.erb
$('.modal').modal();
$("#modal").html("<%= escape_javascript(render '/agencies/new_agency') %>").modal('open');

app/views/agencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ag:</strong>
  <%= @agency.ag %>
</p>

<p>
  <strong>Address:</strong>
  <%= @agency.address %>
</p>

<%= link_to 'Edit', edit_agency_path(@agency) %> |
<%= link_to 'Back', agencies_path %>